version: 2
# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: dappsteros
before:
  hooks:
  - go generate
  - go run github.com/google/go-licenses@latest check . --disallowed_types=restricted
  - go mod tidy
  - go test -race -v ./...

builds:
- id: dappsteros-amd64
  binary: build/sysroot/usr/bin/dappsteros
  hooks:
    post:
    - upx --best --lzma -v --no-progress "{{ .Path }}"
  env:
  - CC=x86_64-linux-gnu-gcc
  ldflags:
  - -X main.commit={{.Commit}}
  - -X main.date={{.Date}}
  - -X github.com/dappsteros-io/DappsterOS/drivers/google_drive.client_id={{.Env.GoogleID}}
  - -X github.com/dappsteros-io/DappsterOS/drivers/google_drive.client_secret={{.Env.GoogleSecret}}
  - -X github.com/dappsteros-io/DappsterOS/drivers/onedrive.client_id={{.Env.OneDriveID}}
  - -X github.com/dappsteros-io/DappsterOS/drivers/onedrive.client_secret={{.Env.OneDriveSecret}}
  - -X github.com/dappsteros-io/DappsterOS/drivers/dropbox.app_key={{.Env.DropboxKey}}
  - -X github.com/dappsteros-io/DappsterOS/drivers/dropbox.app_secret={{.Env.DropboxSecret}}
  - -s
  - -w
  - -extldflags "-static"
  tags:
  - musl
  - netgo
  - osusergo
  goos:
  - linux
  goarch:
  - amd64
- id: dappsteros-arm64
  binary: build/sysroot/usr/bin/dappsteros
  # hooks:
  #   post:
  #     - upx --best --lzma -v --no-progress "{{ .Path }}"
  env:
  - CC=aarch64-linux-gnu-gcc
  ldflags:
  - -X main.commit={{.Commit}}
  - -X main.date={{.Date}}
  - -X github.com/dappsteros-io/DappsterOS/drivers/google_drive.client_id={{.Env.GoogleID}}
  - -X github.com/dappsteros-io/DappsterOS/drivers/google_drive.client_secret={{.Env.GoogleSecret}}
  - -X github.com/dappsteros-io/DappsterOS/drivers/onedrive.client_id={{.Env.OneDriveID}}
  - -X github.com/dappsteros-io/DappsterOS/drivers/onedrive.client_secret={{.Env.OneDriveSecret}}
  - -X github.com/dappsteros-io/DappsterOS/drivers/dropbox.app_key={{.Env.DropboxKey}}
  - -X github.com/dappsteros-io/DappsterOS/drivers/dropbox.app_secret={{.Env.DropboxSecret}}
  - -s
  - -w
  - -extldflags "-static"
  tags:
  - musl
  - netgo
  - osusergo
  goos:
  - linux
  goarch:
  - arm64
- id: dappsteros-arm-7
  binary: build/sysroot/usr/bin/dappsteros
  hooks:
    post:
    - upx --best --lzma -v --no-progress "{{ .Path }}"
  env:
  - CC=arm-linux-gnueabihf-gcc
  ldflags:
  - -X main.commit={{.Commit}}
  - -X main.date={{.Date}}
  - -X github.com/dappsteros-io/DappsterOS/drivers/google_drive.client_id={{.Env.GoogleID}}
  - -X github.com/dappsteros-io/DappsterOS/drivers/google_drive.client_secret={{.Env.GoogleSecret}}
  - -X github.com/dappsteros-io/DappsterOS/drivers/onedrive.client_id={{.Env.OneDriveID}}
  - -X github.com/dappsteros-io/DappsterOS/drivers/onedrive.client_secret={{.Env.OneDriveSecret}}
  - -X github.com/dappsteros-io/DappsterOS/drivers/dropbox.app_key={{.Env.DropboxKey}}
  - -X github.com/dappsteros-io/DappsterOS/drivers/dropbox.app_secret={{.Env.DropboxSecret}}
  - -s
  - -w
  - -extldflags "-static"
  tags:
  - musl
  - netgo
  - osusergo
  goos:
  - linux
  goarch:
  - arm
  goarm:
  - "7"
- id: dappsteros-migration-tool-amd64
  binary: build/sysroot/usr/bin/dappsteros-migration-tool
  hooks:
    post:
    - upx --best --lzma -v --no-progress "{{ .Path }}"
  main: ./cmd/migration-tool
  env:
  - CC=x86_64-linux-gnu-gcc
  ldflags:
  - -X main.commit={{.Commit}}
  - -X main.date={{.Date}}
  - -s
  - -w
  - -extldflags "-static"
  tags:
  - musl
  - netgo
  - osusergo
  goos:
  - linux
  goarch:
  - amd64
- id: dappsteros-migration-tool-arm64
  binary: build/sysroot/usr/bin/dappsteros-migration-tool
  # hooks:
  #   post:
  #     - upx --best --lzma -v --no-progress "{{ .Path }}"
  main: ./cmd/migration-tool
  env:
  - CC=aarch64-linux-gnu-gcc
  ldflags:
  - -X main.commit={{.Commit}}
  - -X main.date={{.Date}}
  - -s
  - -w
  - -extldflags "-static"
  tags:
  - musl
  - netgo
  - osusergo
  goos:
  - linux
  goarch:
  - arm64
- id: dappsteros-migration-tool-arm-7
  binary: build/sysroot/usr/bin/dappsteros-migration-tool
  hooks:
    post:
    - upx --best --lzma -v --no-progress "{{ .Path }}"
  main: ./cmd/migration-tool
  env:
  - CC=arm-linux-gnueabihf-gcc
  ldflags:
  - -X main.commit={{.Commit}}
  - -X main.date={{.Date}}
  - -s
  - -w
  - -extldflags "-static"
  tags:
  - musl
  - netgo
  - osusergo
  goos:
  - linux
  goarch:
  - arm
  goarm:
  - "7"
archives:
- name_template: >-
    {{ .Os }}-{{- if eq .Arch "arm" }}arm-7{{- else }}{{ .Arch }}{{- end }}-{{ .ProjectName }}-v{{ .Version }}
  id: dappsteros
  builds:
  - dappsteros-amd64
  - dappsteros-arm64
  - dappsteros-arm-7
  files:
  - build/**/*
- name_template: >-
    {{ .Os }}-{{- if eq .Arch "arm" }}arm-7{{- else }}{{ .Arch }}{{- end }}-{{ .ProjectName }}-migration-tool-v{{ .Version }}
  id: dappsteros-migration-tool
  builds:
  - dappsteros-migration-tool-amd64
  - dappsteros-migration-tool-arm64
  - dappsteros-migration-tool-arm-7
  files:
  - build/sysroot/etc/**/*
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"
# release:
#   github:
#     owner: dappsteros-io
#     name: DappsterOS
#   draft: true
#   prerelease: auto
#   mode: replace
#   name_template: "v{{ .Version }}"
release:
  github:
    owner: dappsteros-io
    name: DappsterOS
  draft: true
  prerelease: auto
  mode: replace
  name_template: "v{{ .Version }}"
